"""add_last_activity_to_user_wallet

Revision ID: 105b4511d5ca
Revises: 6c6b45ffe090
Create Date: 2026-06-03 15:49:48.553736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "105b4511d5ca"
down_revision: Union[str, None] = "6c6b45ffe090"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_wallet", sa.Column("last_activity", mysql.BIGINT(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_wallet", "last_activity")
    # ### end Alembic commands ###
